/* generated by scripts/prepare-atmosphere.mjs — do not edit */
export interface Atmo { id: string; w: number; h: number; aspect: number; avif1600: string; webp1600: string; avif800: string; webp800: string; target: string }
export const atmosphere: Atmo[] = [
  {
    "id": "elif-00-hero",
    "w": 1600,
    "h": 2000,
    "aspect": 0.8,
    "avif1600": "/atmosphere/elif-00-hero-1600.avif",
    "webp1600": "/atmosphere/elif-00-hero-1600.webp",
    "avif800": "/atmosphere/elif-00-hero-800.avif",
    "webp800": "/atmosphere/elif-00-hero-800.webp",
    "target": "/atmosphere/elif-00-hero-target.webp"
  },
  {
    "id": "elif-01-murekkep-damlasi",
    "w": 1600,
    "h": 2000,
    "aspect": 0.8,
    "avif1600": "/atmosphere/elif-01-murekkep-damlasi-1600.avif",
    "webp1600": "/atmosphere/elif-01-murekkep-damlasi-1600.webp",
    "avif800": "/atmosphere/elif-01-murekkep-damlasi-800.avif",
    "webp800": "/atmosphere/elif-01-murekkep-damlasi-800.webp",
    "target": "/atmosphere/elif-01-murekkep-damlasi-target.webp"
  },
  {
    "id": "elif-02-cam-parcalari",
    "w": 1672,
    "h": 941,
    "aspect": 1.7768,
    "avif1600": "/atmosphere/elif-02-cam-parcalari-1600.avif",
    "webp1600": "/atmosphere/elif-02-cam-parcalari-1600.webp",
    "avif800": "/atmosphere/elif-02-cam-parcalari-800.avif",
    "webp800": "/atmosphere/elif-02-cam-parcalari-800.webp",
    "target": "/atmosphere/elif-02-cam-parcalari-target.webp"
  },
  {
    "id": "elif-03-portal-cerceveler",
    "w": 1672,
    "h": 940,
    "aspect": 1.7787,
    "avif1600": "/atmosphere/elif-03-portal-cerceveler-1600.avif",
    "webp1600": "/atmosphere/elif-03-portal-cerceveler-1600.webp",
    "avif800": "/atmosphere/elif-03-portal-cerceveler-800.avif",
    "webp800": "/atmosphere/elif-03-portal-cerceveler-800.webp",
    "target": "/atmosphere/elif-03-portal-cerceveler-target.webp"
  },
  {
    "id": "elif-04-renk-kartelasi",
    "w": 1536,
    "h": 1024,
    "aspect": 1.5,
    "avif1600": "/atmosphere/elif-04-renk-kartelasi-1600.avif",
    "webp1600": "/atmosphere/elif-04-renk-kartelasi-1600.webp",
    "avif800": "/atmosphere/elif-04-renk-kartelasi-800.avif",
    "webp800": "/atmosphere/elif-04-renk-kartelasi-800.webp",
    "target": "/atmosphere/elif-04-renk-kartelasi-target.webp"
  },
  {
    "id": "elif-05-kinetik-kurdele",
    "w": 1672,
    "h": 941,
    "aspect": 1.7768,
    "avif1600": "/atmosphere/elif-05-kinetik-kurdele-1600.avif",
    "webp1600": "/atmosphere/elif-05-kinetik-kurdele-1600.webp",
    "avif800": "/atmosphere/elif-05-kinetik-kurdele-800.avif",
    "webp800": "/atmosphere/elif-05-kinetik-kurdele-800.webp",
    "target": "/atmosphere/elif-05-kinetik-kurdele-target.webp"
  },
  {
    "id": "elif-06-renk-makinesi",
    "w": 1536,
    "h": 1024,
    "aspect": 1.5,
    "avif1600": "/atmosphere/elif-06-renk-makinesi-1600.avif",
    "webp1600": "/atmosphere/elif-06-renk-makinesi-1600.webp",
    "avif800": "/atmosphere/elif-06-renk-makinesi-800.avif",
    "webp800": "/atmosphere/elif-06-renk-makinesi-800.webp",
    "target": "/atmosphere/elif-06-renk-makinesi-target.webp"
  },
  {
    "id": "elif-07-halftone-kure",
    "w": 1536,
    "h": 1024,
    "aspect": 1.5,
    "avif1600": "/atmosphere/elif-07-halftone-kure-1600.avif",
    "webp1600": "/atmosphere/elif-07-halftone-kure-1600.webp",
    "avif800": "/atmosphere/elif-07-halftone-kure-800.avif",
    "webp800": "/atmosphere/elif-07-halftone-kure-800.webp",
    "target": "/atmosphere/elif-07-halftone-kure-target.webp"
  },
  {
    "id": "elif-08-holografik-kartvizit",
    "w": 1536,
    "h": 1024,
    "aspect": 1.5,
    "avif1600": "/atmosphere/elif-08-holografik-kartvizit-1600.avif",
    "webp1600": "/atmosphere/elif-08-holografik-kartvizit-1600.webp",
    "avif800": "/atmosphere/elif-08-holografik-kartvizit-800.avif",
    "webp800": "/atmosphere/elif-08-holografik-kartvizit-800.webp",
    "target": "/atmosphere/elif-08-holografik-kartvizit-target.webp"
  },
  {
    "id": "elif-09-atolye-masasi",
    "w": 1536,
    "h": 1024,
    "aspect": 1.5,
    "avif1600": "/atmosphere/elif-09-atolye-masasi-1600.avif",
    "webp1600": "/atmosphere/elif-09-atolye-masasi-1600.webp",
    "avif800": "/atmosphere/elif-09-atolye-masasi-800.avif",
    "webp800": "/atmosphere/elif-09-atolye-masasi-800.webp",
    "target": "/atmosphere/elif-09-atolye-masasi-target.webp"
  },
  {
    "id": "elif-10-paylasim-genis",
    "w": 2048,
    "h": 768,
    "aspect": 2.6667,
    "avif1600": "/atmosphere/elif-10-paylasim-genis-1600.avif",
    "webp1600": "/atmosphere/elif-10-paylasim-genis-1600.webp",
    "avif800": "/atmosphere/elif-10-paylasim-genis-800.avif",
    "webp800": "/atmosphere/elif-10-paylasim-genis-800.webp",
    "target": "/atmosphere/elif-10-paylasim-genis-target.webp"
  },
  {
    "id": "elif-10-paylasim-og-1200x630",
    "w": 1200,
    "h": 630,
    "aspect": 1.9048,
    "avif1600": "/atmosphere/elif-10-paylasim-og-1200x630-1600.avif",
    "webp1600": "/atmosphere/elif-10-paylasim-og-1200x630-1600.webp",
    "avif800": "/atmosphere/elif-10-paylasim-og-1200x630-800.avif",
    "webp800": "/atmosphere/elif-10-paylasim-og-1200x630-800.webp",
    "target": "/atmosphere/elif-10-paylasim-og-1200x630-target.webp"
  }
];
export const atmo = (id: string): Atmo | undefined => atmosphere.find((a) => a.id === id);
