/* generated by scripts/prepare-content.mjs — do not edit */
import type { Category } from "@/i18n/dict";
import type { Localized } from "../../content/site";

export interface WorkImage { src: string; w: number; h: number; blur: string }
export interface Work {
  slug: string;
  category: Category;
  year: number | null;
  role: Localized | null;
  tools: string[];
  title: Localized;
  text: Localized;
  client: string | null;
  sample: boolean;
  order: number;
  cover: { src2048: string; src1024: string; src640: string; w: number; h: number; blur: string };
  gallery: WorkImage[];
}
export const works: Work[] = [
  {
    "slug": "ornek-afis-izgara",
    "category": "poster",
    "year": 2026,
    "role": {
      "tr": "Tasarım",
      "en": "Design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Izgara Üzerine",
      "en": "On the Grid"
    },
    "text": {
      "tr": "Sekiz kolonlu bir ızgaranın kendisini afişe dönüştüren tipografik bir çalışma. Tek renk, tek yazı, tek jest.",
      "en": "A typographic study that turns an eight-column grid into the poster itself. One colour, one face, one gesture."
    },
    "client": null,
    "sample": true,
    "order": 1,
    "cover": {
      "src2048": "/works/ornek-afis-izgara/cover-2048.webp",
      "src1024": "/works/ornek-afis-izgara/cover-1024.webp",
      "src640": "/works/ornek-afis-izgara/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACQBACdASoYAB4APu1irVAppSQisBgIATAdiWwAvkg1f/o6xmIeGCJRYu3nSAAA/vHpm2YidWqKS6Zsrp/o6lRqckQgVzSP83f3/KE4+Z68fRy14zC2wZoGxIiCr+gb7gSLO6iYdrMRB0l5MSNKsMcnpDQn5geG+Fgp8nhM4dVA4ldzUviA/HisHc1jB/QAAAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-izgara/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwBACdASoYAB4APu1ys1MppqSkKAgBMB2JagDHDvAt/8A9D+XjpAc278aYkd4gAP7tMuRcjUtGcm1ywg18KsFlXvZOxKHju4WUa6bozgxjaoHz4uC/4Z1LDfPWSOzN/dbisyckxr2oNHFGAAA="
      },
      {
        "src": "/works/ornek-afis-izgara/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoYAB4APu1irFAppSQisBgIATAdiWwAAJJ/7k7m6+P2FCNT/TyAAP70O2kdp8SYebGjwNLN8WFlgUt0Hc0+5KMH+BtRHT150RHrP+o35UoXCSyMnhJDabtAjMefvP8kqHVY569BJz+sLzbd790ShOfP+kfEjvA25KITdDjKNTqDg/5oVSGMAAAA"
      }
    ]
  },
  {
    "slug": "ornek-afis-daireler",
    "category": "poster",
    "year": 2026,
    "role": {
      "tr": "Tasarım",
      "en": "Design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Eş Merkezli",
      "en": "Concentric"
    },
    "text": {
      "tr": "Eş merkezli daireler ve bir siyah bant. Bir konser dizisi için tasarlanmış afiş örneği.",
      "en": "Concentric circles and one black bar. A sample poster for a concert series."
    },
    "client": null,
    "sample": true,
    "order": 2,
    "cover": {
      "src2048": "/works/ornek-afis-daireler/cover-2048.webp",
      "src1024": "/works/ornek-afis-daireler/cover-1024.webp",
      "src640": "/works/ornek-afis-daireler/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAABQBgCdASoYAB4APu1mpU4ppaMiMBgMATAdiUAZWL/88AVQuGAGdLhE20vH/QAg9iNCgdpuzLZEFkgqwAD+7W8x4EXt+4DtgObnVT3OG/0yNHZqHQEuBWC1wJqDfGavZ3PK1AdY4Eu+HgcUCenjoHwhylQPeJHRhWzUqUi7yzoOs5hKQUz9OXE85yfQw4FJLF5lPgcD9rSlhVcjwxW4Y2Fr8lGfPJI/q/nK0vDcihL10HKborAlFddRXkdWkBIZpGUL6pP5s3Q8UOC+S/Jr0WiiRh3V0YCZzWS2M/tTBlIAAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-daireler/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRmIBAABXRUJQVlA4IFYBAACQCACdASoYAB4APu1krFAppSQisBgIATAdiWIAv2s0d/9tHmc9Bz7GmAQIH0E6qigJUD3Dj7/yMyjsxPbG+8CHRsGht49Q0GcKYnTyAAD+7VzVYYxzBvEy1gRk0njig2SuPksr2aErEMMBMUiexdlQqbw1kujqs6HSp+n2gyTWL6xwZudxRCZXb0BEUYlcO4W23AZD+YFAiidjYaAikocVCnfkkS2C21hkCmIbNLtiwYb8Lw8HaL0boehQz5aICZ6aRj0tEBC8yyfwQFP1RIOvZdAzTKOk3fpyfXd63YgoON4eiENss3X+hk3T126zKf0raleo2FpAUMTi7HfPSjU2E+Lrd0JSQGuVNHY0nt6IfQ5Ni4EoWDqQJYTf0Q0tHbeQn8UfWH6KXlHlndhD75K36T3Cm1Xh0x08RGwBys48QxxVHkP9rUJmvgDrC2j3KKfwSuyacAA="
      },
      {
        "src": "/works/ornek-afis-daireler/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAACQBQCdASoYAB4APuVgo02pJaMiMAwBIByJQBmcP/ycMDEaNwStUZnBfVyHAJKpPySBFYqwAAD+8Oyyuv8AyGudH97tBJcpPGQGcjf2wJnV6z0Cjj1b6eYjkVapmeWKPgMAnWoD5UEkjFMZ50gvfUdWzW0DBMMDs7kamzSDOSPaA6SbfZb1zzmhs6wcoLQM/m8cqGi+RWJ2cT+kzyx0/kF2Zj8ADtlszB1Zb8+magued9hKvAHeUH2gGz0tuBIuuSUZjeQtPgs5aBJD5X6iruDjMABoNzieCARZ1oAA"
      }
    ]
  },
  {
    "slug": "ornek-afis-yedi",
    "category": "poster",
    "year": 2026,
    "role": {
      "tr": "Tasarım",
      "en": "Design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Yedi",
      "en": "Seven"
    },
    "text": {
      "tr": "Nokta ızgarasından büyüyen tek bir rakam. Baskıda nokta sıklığı kâğıdın dokusuyla birleşir.",
      "en": "A single numeral growing out of a dot grid. In print, the dot frequency merges with the paper's grain."
    },
    "client": null,
    "sample": true,
    "order": 3,
    "cover": {
      "src2048": "/works/ornek-afis-yedi/cover-2048.webp",
      "src1024": "/works/ornek-afis-yedi/cover-1024.webp",
      "src640": "/works/ornek-afis-yedi/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoYAB4APtFWok2oJKMiN+gBABoJQBmaBjRT59zuWZYGY9sACgAA/vHM+jY9V8TgWp0uCC7UwTT1j4/PEAK9Exvx15eDC7GafGerUfyZISnj7lOiOYh8EG3AfJjrAGijGool/jc6xK6p/pz7D97yG7DjE9pr6K3gAAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-yedi/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAAAwBgCdASoYAB4APtleo02oJaMiN/qoAQAbCWgArj02ZcATZMMNtPnwUnJj7k0FOZKA5UVnFWrWNeAAAP7zcnIvZ4O/YyR1aCviWcarUZHAe+BQma1lb1mfTre1aTWxVpCZuZFBqDqNrPF2Uz/3JFreTsvQUGjDorHoLO0cirftYbw+7AZBjzcSAhObI/dRgIinhUuLb0YExYojc2zeYTowtJ2oKe9RRKN69JG9HAeu1WwwWCLkxUXx/zzHZxrXxeggIhASN8rwGdPtanyzOAvvbwVjDoeePH5g0IAA"
      },
      {
        "src": "/works/ornek-afis-yedi/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoYAB4APtFYok2oJSMiN+gBABoJQBh1hjRT+YJA2foshPTpUWgAAP70JMn49RHhTMGy0qrXztZTrG6ev6NWoFAwOxh6B2CZuenVuK3/CBhEZuxWLNCMTZ7lPQgwW/YCuwCdG0peO6sHBEethRmPbOYt0Zk8zF0GeIAAAA=="
      }
    ]
  },
  {
    "slug": "ornek-kitap-kagit",
    "category": "editorial",
    "year": 2026,
    "role": {
      "tr": "Tasarım",
      "en": "Design"
    },
    "tools": [
      "InDesign",
      "Illustrator"
    ],
    "title": {
      "tr": "Kâğıt Üzerine",
      "en": "On Paper"
    },
    "text": {
      "tr": "Bir deneme kitabı için kapak ve iç düzen örneği. Serif başlık, dar sütun, geniş kenar boşluğu.",
      "en": "Cover and interior layout sample for a book of essays. Serif title, narrow measure, generous margins."
    },
    "client": null,
    "sample": true,
    "order": 4,
    "cover": {
      "src2048": "/works/ornek-kitap-kagit/cover-2048.webp",
      "src1024": "/works/ornek-kitap-kagit/cover-1024.webp",
      "src640": "/works/ornek-kitap-kagit/cover-640.webp",
      "w": 1500,
      "h": 2100,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoYACIAPu1uq08ppyOiMBVYATAdiUAZ1gFm2Pi6h8UONatVhwAA/guaKWgouJGtVB9a3TjQpZ/GKuFc2ETRXkj0pvUAOhs33GQ91iGf4AisAEPn1U+gAAAA"
    },
    "gallery": [
      {
        "src": "/works/ornek-kitap-kagit/gallery-1-1600.webp",
        "w": 1600,
        "h": 2240,
        "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwBACdASoYACIAPu1qrE8ppiQiKrgMATAdiWkAzuwLNtnheh4iiItTthFlssMAAP7tPOmada4q6kg0HVWoYu+5d+1UtoHg76/YGI01qtPDKlIx8eOSi3zlFJayyaWo5HvpgQNnqlOYD4QSwt5rXdPTDfF7KlhklYay/EOIj2hwAAAA"
      },
      {
        "src": "/works/ornek-kitap-kagit/gallery-2-1600.webp",
        "w": 1500,
        "h": 2100,
        "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoYACIAPu1oqk2ppiQiMAgBMB2JQBnWBDvlv3q4TGuC7qAAAP5PhmmkqOWBlCoQ+obrB4kmoU1PDh/rmreq38AzxSMv5GHCVAURV4ORNFgs8q+whhzX4AAA"
      }
    ]
  },
  {
    "slug": "ornek-ambalaj-etiket",
    "category": "packaging",
    "year": 2026,
    "role": {
      "tr": "Tasarım",
      "en": "Design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Atölye Etiketi",
      "en": "Studio Label"
    },
    "text": {
      "tr": "Bir kâğıt kutusu için sarmalayan etiket. Ön yüzde mühür, yan yüzlerde ürün bilgisi.",
      "en": "A wrap-around label for a paper box. A seal on the front, product information on the sides."
    },
    "client": null,
    "sample": true,
    "order": 5,
    "cover": {
      "src2048": "/works/ornek-ambalaj-etiket/cover-2048.webp",
      "src1024": "/works/ornek-ambalaj-etiket/cover-1024.webp",
      "src640": "/works/ornek-ambalaj-etiket/cover-640.webp",
      "w": 2000,
      "h": 1400,
      "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoYABEAPu1wsVIppqSiqAgBMB2JZgCxDKtJ/k5+DaAnEXJ0TUVTKsfgAP6yP3ew7CskpL+MjlcSjQi3TUZ5HMc7eqSLHfH41wZsYqehZmHj9y7wQu91hucgdNPuwuf/SbP/6gz//UGfn7/xv9WvkyugxIAAAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-ambalaj-etiket/gallery-1-1600.webp",
        "w": 1600,
        "h": 1120,
        "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABwBACdASoYABEAPuVgpk2pJaOiMAwBIByJaQDKACHf4OVbARKHWOzws51OOAD+77O2gOSSkdGvrIGSeH/H+/wpc1WV8xrcq+Bu8CpMniEwgJnv9cAAAA=="
      },
      {
        "src": "/works/ornek-ambalaj-etiket/gallery-2-1600.webp",
        "w": 1600,
        "h": 1120,
        "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoYABEAPu1wsFKppiSiqAgBMB2JZAC29oBcqARHKy27vOwJhQHAAP7OByiP2OiySmuEUeDSCoVDDJY/cYg4ACeGEgfCJTSLtBXM0RJL0JoFgkum2RzQ+rtV/9NI/40j/jSPmLftTBJGTkAAAAA="
      }
    ]
  },
  {
    "slug": "ornek-kimlik-eg",
    "category": "identity",
    "year": 2026,
    "role": {
      "tr": "Tasarım",
      "en": "Design"
    },
    "tools": [
      "Illustrator"
    ],
    "title": {
      "tr": "EG Monogramı",
      "en": "EG Monogram"
    },
    "text": {
      "tr": "İki harfin tek bir çizgide buluştuğu monogram; kartvizitte kör kabartma, afişte tek renk.",
      "en": "A monogram where two letters meet in one stroke; blind-embossed on the card, single colour on the poster."
    },
    "client": null,
    "sample": true,
    "order": 6,
    "cover": {
      "src2048": "/works/ornek-kimlik-eg/cover-2048.webp",
      "src1024": "/works/ornek-kimlik-eg/cover-1024.webp",
      "src640": "/works/ornek-kimlik-eg/cover-640.webp",
      "w": 1600,
      "h": 1600,
      "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYABgAPu1oq08ppiOiMBgIATAdiUAYObF4Tfa3udGmgxijcqsgAP7tNx3uzSRtoH80hmcbFp0eMA4boUSe9Nu/nlyicvM/H/Ng0BlXMjfPCQyLJ51HrxZwXjCCh1Eov+nQ4Tnr9OFnW70P0pT51gij2QuQ4CHG+RNKwgHWzDIyWI21SLZuvwN333I+rt5XYAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-kimlik-eg/gallery-1-1600.webp",
        "w": 1600,
        "h": 1600,
        "blur": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4INQAAADwBACdASoYABgAPu1qsFCppaSiqAqpMB2JaAAD5Ds2/gIa6dhHBP5wsCkKxgkrRMAA/vNpNeMV9K0eDBxHV4L9pIMd9BGlf+2clxPMb6Maocc3/ww6LffPQj/lnyLjdjNw/HtadM0+AAB5gwNPW78nv0fT/z6mjbKZB9yXZhss10lur2rhSFtNdnhsHAibBO3naMP1Ee8TXnpU9QWUfv3qfg3Ncv26e689NdsAcpXoRyX6Q0+VxmNK7xH+JWS1WiGRHLnBZGKnere+Mx5TbCFiUWhgAA=="
      },
      {
        "src": "/works/ornek-kimlik-eg/gallery-2-1600.webp",
        "w": 1600,
        "h": 1600,
        "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoYABgAPu1oq08ppiOiMBgIATAdiUAXqwId/CHj69DBxk1XtsAA/vC9TwOu2wDiXSHFXJfngPS5jTlUA3cjurIrWZBoK8HlzpUIMYol/zkuTodkopyb4Y3YWpGDY3+gzuLqHH5xPGVCJPspGzCxgY8WX6S8hh9mgXBya3E54z7DEsfQ9MfYs9CC0AdzH7jJyiwAAA=="
      }
    ]
  }
];
export const portrait: WorkImage | null = null;
