/* generated by scripts/prepare-content.mjs — do not edit */
import type { Category } from "@/i18n/dict";
import type { Localized } from "../../content/site";

export interface WorkImage { src: string; w: number; h: number; blur: string }
export interface Work {
  slug: string;
  category: Category;
  year: number | null;
  role: Localized | null;
  tools: string[];
  title: Localized;
  text: Localized;
  client: string | null;
  sample: boolean;
  order: number;
  cover: { src2048: string; src1024: string; src640: string; w: number; h: number; blur: string };
  gallery: WorkImage[];
  /** three dominant colours of the cover, most frequent first */
  colors: string[];
  /** optional depth layers, back to front */
  layers: WorkImage[];
}
export const works: Work[] = [
  {
    "slug": "ornek-afis-izgara",
    "category": "poster",
    "colors": [
      "#f2f1ec",
      "#262e7a",
      "#999cbf"
    ],
    "layers": [
      {
        "src": "/works/ornek-afis-izgara/layer-1-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      },
      {
        "src": "/works/ornek-afis-izgara/layer-2-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      },
      {
        "src": "/works/ornek-afis-izgara/layer-3-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      }
    ],
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Izgara Üzerine",
      "en": "On the Grid"
    },
    "text": {
      "tr": "Bir tipografi sergisi için afiş: sekiz kolonlu ızgara, sayfayı dolduran tek bir sözcük ve üst baskıyla çakışan iki mürekkep.",
      "en": "Poster for a typography exhibition: an eight-column grid, one word filling the sheet and two inks meeting in overprint."
    },
    "client": null,
    "sample": true,
    "order": 1,
    "cover": {
      "src2048": "/works/ornek-afis-izgara/cover-2048.webp",
      "src1024": "/works/ornek-afis-izgara/cover-1024.webp",
      "src640": "/works/ornek-afis-izgara/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4INQAAABQBQCdASoYAB4APu1iq0+ppSOiMBgIATAdiWwAvkg03NyarlSuDME5gYtKD7dSAiwJgAAA/vOKPK/mjX5DmOzG4nItri727ixoX1jg0tVwkgvPbSuNc9LmzgbVNLP52OE0rdv8xMEe4aMxZGkopulVaJLOLUltHN+LMn3qnCRBp6IIFJdfyBgrhmg7ZFznqp9nBuHvz1Sgm0sXwcvNWYOQvCCklszvAB/PqueeOQpjO2hJHjT8u1zrCyije7Fa0ZfbO0NSgm+zifWVz4CJalQhZ0ngAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-izgara/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoYAB4APtVWok2oJKMiN+gBABqJbACdEfqgWZzuSEz0dFrPapVoQAD+82/t3w75qm5Jkm6GYIp7E98UzrT3z/n92rvMIpZgTMAPa7z7uY6Lg9gO5qQ7kG4avsv47WNldIEovZ9SWv7GipuN/+/PtA15LM4VlFCT3HYFFd1F063NNqVmd7eKjkAA"
      },
      {
        "src": "/works/ornek-afis-izgara/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4INQAAAAQBQCdASoYAB4APu1kq0+ppSOiMBgIATAdiWwAAJBpygHuPy+EAVcaYpeQHwalgRUAAP71g4DLdJy8n88B9zCwdWv4XX5Yr68MyxKRlrQVPJ2CIunH5Xv3yu6KvalcaycUB/tkqH5RIVsArxlYOXqWCZYDSYckKw79H7RCEbzFOOfaOaYbWlZi9yYiaqOyyNBqtVzXY4yF1OGqMWTRM/EQ4pm31QSIq7IhYydhf8wqCw2bxOhPUimH1sS9nr5Edtgi4KJo/VYsJQKgiNswfEoBvyBAAA=="
      }
    ]
  },
  {
    "slug": "ornek-afis-daireler",
    "category": "poster",
    "colors": [
      "#dad9d4",
      "#1b1c1e",
      "#9ca1e6"
    ],
    "layers": [
      {
        "src": "/works/ornek-afis-daireler/layer-1-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      },
      {
        "src": "/works/ornek-afis-daireler/layer-2-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      },
      {
        "src": "/works/ornek-afis-daireler/layer-3-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      }
    ],
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Sessiz Seri",
      "en": "Quiet Series"
    },
    "text": {
      "tr": "Altı akşamlık bir konser dizisi için afiş. Eş merkezli halkalar ses dalgasıdır; siyah bant sahnenin kendisi.",
      "en": "Poster for a six-evening concert series. The concentric rings are the sound; the black bar is the stage."
    },
    "client": null,
    "sample": true,
    "order": 2,
    "cover": {
      "src2048": "/works/ornek-afis-daireler/cover-2048.webp",
      "src1024": "/works/ornek-afis-daireler/cover-1024.webp",
      "src640": "/works/ornek-afis-daireler/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAADwBQCdASoYAB4APu1mp02ppiOiMBgMATAdiUAZQ2v9t/gHom3cqNwK1SSewELmb5PL8ZxX19XAAAD+7UrjMfhlRmaSRjMOeOPUpcWu8MSe3X8MInSRBqUV6GVlf1ILRERPQjMKHn7gQIEBAaju6zVzPpRUBAhQb8zpbGjZHCPurICklp1y1DEdbfOLvdiGbyR1PQIG/fAQuJciuh4LE8PsccqBX1mbThXBaVHsw1webcSGOc9y8C/o2kz7Q1r1vO7M6nbc26qqbtMe6ranf5LREAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-daireler/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRnIBAABXRUJQVlA4IGYBAADQBwCdASoYAB4APu1qsFAppaSiqAqpMB2JagDE+E3Jx6YBvLk+B8KrcG+BpPvWfP+55phfq2XN+NfYWeAjgN5gFbNGI2iM4AD+7WFsYwbulGqO5Jd7AbmEZWLGpkfJjIM+xz/qJixZQyg5i7ZPBkGZaG+Dd255q750bL1ZqWo6QpBIiB9vsBRwAYkz4G+N6GlzxK1T2rjECfbqITIIOZk6Ry/YtSajQ+NIsiv0/4QSUrQXL5o3Mv9fXPv/yKshm46SEEnwZNlJ2jxIjesekF/oCZnp6M6/6sYe+4JGeNYjAstJOq+mccwbmzpCdmPC4a1VsKbSVxFWQDO4iPTEihe0HVcm//HkBwNDEJZaQMV5B8tmrpFJLLqtZQcP8a7EozLP86/cDCj9E/sGBVR6+KOwrO31mXvmHtVRhH6Hx0xJXvvOVKX+l1Z7MyiPG+tal56ZNx93p5JrteEOifxzT6ecojCYkAAA"
      },
      {
        "src": "/works/ornek-afis-daireler/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAADQBQCdASoYAB4APu1mpk2ppiOiMBgMATAdiUAZnhV//7b/APRLhfEI74UZs7715naX7KVcC+uAAP7wznUjDzkvtPVdwNGnZ5soJJi3pe4buMHcYhFriBs7a3FJOr7lLiM1ZdLYVh3VAHDciq9+JJo65XrpXQc0yEHR0GzvkBx98Yx36o1mZRKLsAVGV/BTscfVbxkUOcl3PAqaJASJyEzmTqCTWOgW+mO3Ddm36yTtG8n3VlCH83JLwI4aLLl7cLAe7kn3R7Cy7+BhlSxriscAAAA="
      }
    ]
  },
  {
    "slug": "ornek-afis-yedi",
    "category": "poster",
    "colors": [
      "#efeeea",
      "#cfcfd1",
      "#4f5be9"
    ],
    "layers": [
      {
        "src": "/works/ornek-afis-yedi/layer-1-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      },
      {
        "src": "/works/ornek-afis-yedi/layer-2-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      },
      {
        "src": "/works/ornek-afis-yedi/layer-3-1024.webp",
        "w": 1024,
        "h": 1280,
        "blur": ""
      }
    ],
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Yedi",
      "en": "Seven"
    },
    "text": {
      "tr": "Atölyenin yedinci yılı için afiş: halftone bir gradyanın içinden büyüyen tek rakam, kâğıdın dokusuyla birleşen nokta sıklığı.",
      "en": "Poster for the studio's seventh year: a single numeral growing out of a halftone gradient whose dots merge with the paper's grain."
    },
    "client": null,
    "sample": true,
    "order": 3,
    "cover": {
      "src2048": "/works/ornek-afis-yedi/cover-2048.webp",
      "src1024": "/works/ornek-afis-yedi/cover-1024.webp",
      "src640": "/works/ornek-afis-yedi/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoYAB4APtVWok2oJKMiN+gBABqJQBj8hjRUQpyCmLwlSUVPk4AA/vNynvzoaUNFGDTox3k9bKqtQv/a81NmsULMrLyxEmU3vKyfgVcdmSFFO4IAvvwqIlV/h9bSPXXdRQsI5cp01xPT9/gVD6SFcOUupmmhcf7GF8pgAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-yedi/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBQCdASoYAB4APuFUpU2opKOiN/qoARAcCWYAxw9WwOTvBOl0I0xC7a2xL10G7DJRCCAA/vfpiNS8ZPa7xYmd3DqGDQ6V/+6OZdMlVEwLmrdmmc9hNfP1ww7GziQUj/rqkTXkjvda9L2QlUYvOXBpUJ2gGD4xa50zESDhvbBYQqjqc5SUZRtQ9rPYtMMBuT7jAiKNWoFIariYd0souoK+ud9jkgAA"
      },
      {
        "src": "/works/ornek-afis-yedi/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoYAB4APtleo02oJaMiN/qoAQAbCUAZsIQtf7fp6qllpxXfHJCAAP70JMn8W5nyGgA3bUAGZZeLYNDQT/304Hu4e+eLAPCn5MzHAqfcIfmI9da0EAvW2CouLqslmaBoWTx8tBla9NMTwt/785q/07Ask4qch0qQAAA="
      }
    ]
  },
  {
    "slug": "ornek-kitap-kagit",
    "category": "editorial",
    "colors": [
      "#f2f1ed",
      "#3646f9",
      "#b7b7b4"
    ],
    "layers": [
      {
        "src": "/works/ornek-kitap-kagit/layer-1-1024.webp",
        "w": 1024,
        "h": 1434,
        "blur": ""
      },
      {
        "src": "/works/ornek-kitap-kagit/layer-2-1024.webp",
        "w": 1024,
        "h": 1434,
        "blur": ""
      },
      {
        "src": "/works/ornek-kitap-kagit/layer-3-1024.webp",
        "w": 1024,
        "h": 1434,
        "blur": ""
      }
    ],
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "InDesign",
      "Illustrator"
    ],
    "title": {
      "tr": "Kâğıt Üzerine",
      "en": "On Paper"
    },
    "text": {
      "tr": "Bir deneme kitabı için kapak ve iç düzen. Serif başlık, dar sütun, geniş kenar boşluğu; sırtta tek renk, kapakta kör kabartma.",
      "en": "Cover and interior for a book of essays. Serif title, narrow measure, generous margins; one colour on the spine, a blind emboss on the cover."
    },
    "client": null,
    "sample": true,
    "order": 4,
    "cover": {
      "src2048": "/works/ornek-kitap-kagit/cover-2048.webp",
      "src1024": "/works/ornek-kitap-kagit/cover-1024.webp",
      "src640": "/works/ornek-kitap-kagit/cover-640.webp",
      "w": 1500,
      "h": 2100,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoYACIAPu1mqk2ppaQiMAgBMB2JQBi5BDwACZPOwHHiQAD9A0Iy1e1HEJd0m96ThnaI9wMFKxEmVyH9oeZf3tNJNwrmulN6gAW3YgLWjyHqcQiw6ZcaIA8RPIAAAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-kitap-kagit/gallery-1-1600.webp",
        "w": 1600,
        "h": 2240,
        "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBQCdASoYACIAPu1orU8ppiQiKrgMATAdiWkA0MwLNnPq4Wl4tgbHfcX7mHsAYAu3AAD+77uJLfdR+ovZXc6vAt/t2YEhxR13jQu0bzdezRXddisG6QMrUTQ9paL0OMRZ51SkBD5LA+SGYxaZO8yxhzYt/SY0pIunRbQ+3JhTNlLRjFiJfzUnQAA="
      },
      {
        "src": "/works/ornek-kitap-kagit/gallery-2-1600.webp",
        "w": 1500,
        "h": 2100,
        "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoYACIAPu1mqk2ppaQiMAgBMB2JQBlPBDwBSl9FBuj8kAAA/k+uGMm6m0/SOEOFE3zxQS0ZVCc7FfLRF9Vv4BnfwL+Rh5Ej6CthTOrmGjUIZmkzMAAAAA=="
      }
    ]
  },
  {
    "slug": "ornek-ambalaj-etiket",
    "category": "packaging",
    "colors": [
      "#f1f0ee",
      "#bbbdd9",
      "#2e3ffb"
    ],
    "layers": [
      {
        "src": "/works/ornek-ambalaj-etiket/layer-1-1024.webp",
        "w": 1024,
        "h": 717,
        "blur": ""
      },
      {
        "src": "/works/ornek-ambalaj-etiket/layer-2-1024.webp",
        "w": 1024,
        "h": 717,
        "blur": ""
      },
      {
        "src": "/works/ornek-ambalaj-etiket/layer-3-1024.webp",
        "w": 1024,
        "h": 717,
        "blur": ""
      }
    ],
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Atölye Etiketi",
      "en": "Studio Label"
    },
    "text": {
      "tr": "Bir kâğıt kutusu için sarmalayan etiket. Ön yüzde mühür, yan yüzlerde ürün bilgisi; kesim çizgileri ve kırım payı bırakılmış.",
      "en": "A wrap-around label for a paper box. A seal on the front, product information on the sides; die-cut and fold allowances left in."
    },
    "client": null,
    "sample": true,
    "order": 5,
    "cover": {
      "src2048": "/works/ornek-ambalaj-etiket/cover-2048.webp",
      "src1024": "/works/ornek-ambalaj-etiket/cover-1024.webp",
      "src640": "/works/ornek-ambalaj-etiket/cover-640.webp",
      "w": 2000,
      "h": 1400,
      "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQBQCdASoYABEAPu1qq08ppiOiMBgIATAdiWgAv2tHIl+QAAZlTxxpOog3l9uf+d1ptRXOAAD+t/IYB7ARqA6wjql7Dunry14dAHDl6r95NzhN4rBzhRcsIfX0Df1MnBfHQxCPNsSjA1qS+RpD69RShEXcb0IMTX5MX5rCcCw7nhPAwsAAAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-ambalaj-etiket/gallery-1-1600.webp",
        "w": 1600,
        "h": 1120,
        "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoYABEAPu1mqk2ppaQiMAgBMB2JaQAAW+s9v9Oobw1JWBTaAAD+77OxB/StFB9SNsMyvXmCER4ymvVdi6auuwgAF8GUoWuke3yTXRLk53s0/ofAAAA="
      },
      {
        "src": "/works/ornek-ambalaj-etiket/gallery-2-1600.webp",
        "w": 1600,
        "h": 1120,
        "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBQCdASoYABEAPu1qsVAppiUiqAqpMB2JaAC/a1oiv5ABr/wPA+nSsZzoQ9b6YoLSjy4AAP7SO+ZUN0VWJ476UieQyPPYZSup9F6lCaWWqJ+MLkunpH7Ed0FTRhXAjQezZAzi1DzPSnLT9wgeLgebHgZ+658hOHxk1BygtC18AA=="
      }
    ]
  },
  {
    "slug": "ornek-kimlik-eg",
    "category": "identity",
    "colors": [
      "#f2f1ee",
      "#7980cf",
      "#161b54"
    ],
    "layers": [
      {
        "src": "/works/ornek-kimlik-eg/layer-1-1024.webp",
        "w": 1024,
        "h": 1024,
        "blur": ""
      },
      {
        "src": "/works/ornek-kimlik-eg/layer-2-1024.webp",
        "w": 1024,
        "h": 1024,
        "blur": ""
      },
      {
        "src": "/works/ornek-kimlik-eg/layer-3-1024.webp",
        "w": 1024,
        "h": 1024,
        "blur": ""
      }
    ],
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator"
    ],
    "title": {
      "tr": "EG Monogramı",
      "en": "EG Monogram"
    },
    "text": {
      "tr": "İki harfin tek bir çizgide buluştuğu monogram; kartvizitte kör kabartma, afişte tek renk, ekranda hareketli.",
      "en": "A monogram where two letters meet in one stroke; blind-embossed on the card, single colour on the poster, animated on screen."
    },
    "client": null,
    "sample": true,
    "order": 6,
    "cover": {
      "src2048": "/works/ornek-kimlik-eg/cover-2048.webp",
      "src1024": "/works/ornek-kimlik-eg/cover-1024.webp",
      "src640": "/works/ornek-kimlik-eg/cover-640.webp",
      "w": 1600,
      "h": 1600,
      "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYABgAPu1kqk+ppSOiMBgIATAdiUAZC4Id+99s2kf7jF/TnRZ8AP7vtex9vreY2cG2dKJHvYZXnj3Ixsd4Af7Hhv9lynXB9oCYahPNJlNRVsACZfVPs9TvmAfpQUjCtGXZdMVgvtn0BptUvamRNMvyJA9Rm87GX3Tg/n16LK8qChxqp/NssEiraYQeBOAAAAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-kimlik-eg/gallery-1-1600.webp",
        "w": 1600,
        "h": 1600,
        "blur": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAABQBQCdASoYABgAPu1sqVCppiOiqA1RMB2JaADLOBPCIsMLrN7KlALSXa983C/StrK8yAAA/visqPvF+iVl/zAfNAucwPeYaBl16Oe9xAEjT9nohWHZfPC8pkKS/WHrL12qjS7xQI1L5WNzrc4Pmhh2mQapQVq1ZqEGNhKmrR+PJ4/Gfcc6+OiMtMUY0U/mkAhjd9tKkDoce5hoz3U1PeLmrl8d94/ofFANhPyV/ug4pIO+uod8MTXGF7PXys27PUSPtZ41zZj9oAAA"
      },
      {
        "src": "/works/ornek-kimlik-eg/gallery-2-1600.webp",
        "w": 1600,
        "h": 1600,
        "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACwBACdASoYABgAPu1kpU2ppaMiMBgMATAdiUAZC4Id+99ui3XcovcVRdMpWwAAAP7ymNKgLnqP6itRbX0ULpyLvdIJWkiTMgDLa/6chvYxiMF1Xwcy4GYTrURcE/Gi06avnLfFj+lOTfBwUFNI59WMVcV84+e5EAHiK2Fc2vFWpOQsL4HQ2cqgLJtTfqr7OEH9+wAA"
      }
    ]
  }
];
export const portrait: WorkImage | null = null;
