/* generated by scripts/prepare-content.mjs — do not edit */
import type { Category } from "@/i18n/dict";
import type { Localized } from "../../content/site";

export interface WorkImage { src: string; w: number; h: number; blur: string }
export interface Work {
  slug: string;
  category: Category;
  year: number | null;
  role: Localized | null;
  tools: string[];
  title: Localized;
  text: Localized;
  client: string | null;
  sample: boolean;
  order: number;
  cover: { src2048: string; src1024: string; src640: string; w: number; h: number; blur: string };
  gallery: WorkImage[];
}
export const works: Work[] = [
  {
    "slug": "ornek-afis-izgara",
    "category": "poster",
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Izgara Üzerine",
      "en": "On the Grid"
    },
    "text": {
      "tr": "Bir tipografi sergisi için afiş: sekiz kolonlu ızgara, sayfayı dolduran tek bir sözcük ve üst baskıyla çakışan iki mürekkep.",
      "en": "Poster for a typography exhibition: an eight-column grid, one word filling the sheet and two inks meeting in overprint."
    },
    "client": null,
    "sample": true,
    "order": 1,
    "cover": {
      "src2048": "/works/ornek-afis-izgara/cover-2048.webp",
      "src1024": "/works/ornek-afis-izgara/cover-1024.webp",
      "src640": "/works/ornek-afis-izgara/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAABwBQCdASoYAB4APu1mq0+ppSOiMBgIATAdiWwAt7g0xTMVOflS9mJ+M8KYpfdAhf/mNMMAAP7zijyO+SuIl6lt6Z3zwogUEc3Xr1tTwojGftjw+yucxnCzS5s4GvV7icOqNgP/H7NvuGhRa2GrD65EqytNg7+MsmwqVpgQMV7sSHE/chcYLgSbKlPIdRI0S/UR+JtMBOsAyIsSETGSERzrxKhgvavNeAIaUM7n7nIJthSL12QA+rR3iy7dhaB86Jonvq5UpyCE+Agyu/u5YRidxbmNvcLQAAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-izgara/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBQCdASoYAB4APtlco02oJaMiN/qoAQAbCWwAnSiskBbZgDv/Ys+f8p7gOHNRnTWsAP7zb+3eohcjrQM1KOpCQ99gWc6ixb4Ky3/yivoAGWjkCU/MA/IQxCN1C8I524V6AxEBj4K1FoN3njAItbkWLORjui/jP1F/Impt4CVg3XdPb73yl+5/6Aoc1SS9vlXfAQAA"
      },
      {
        "src": "/works/ornek-afis-izgara/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAABwBQCdASoYAB4APu1oq08ppiOiMBgIATAdiWwAyJg0xTMQj3N32UtZ9499CLaZG5fo+BBAAP70O2lcynaXCinsmMJddpquJZ9h3D0gZJG7evhb7P6rzTBL60sD7S48t2Sf53Ccthqsh1ndsZ5p/Oje8vepZgRqsKaC+eEcQ7htIzP7ZJC8ei7xn6PzTXqtXduu5+rIF5r2ifxG2rQq1lb+T1tySNVjJDL8OUJMTbs+bvcyS5HeGFaizW5NKivwGisNBQm8yIjoolsKxs1b4hWAAAA="
      }
    ]
  },
  {
    "slug": "ornek-afis-daireler",
    "category": "poster",
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Sessiz Seri",
      "en": "Quiet Series"
    },
    "text": {
      "tr": "Altı akşamlık bir konser dizisi için afiş. Eş merkezli halkalar ses dalgasıdır; siyah bant sahnenin kendisi.",
      "en": "Poster for a six-evening concert series. The concentric rings are the sound; the black bar is the stage."
    },
    "client": null,
    "sample": true,
    "order": 2,
    "cover": {
      "src2048": "/works/ornek-afis-daireler/cover-2048.webp",
      "src1024": "/works/ornek-afis-daireler/cover-1024.webp",
      "src640": "/works/ornek-afis-daireler/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAACwBQCdASoYAB4APuVgpk2pJaOiMAwBIByJQBlo6/23+A2mW+48yIejVv7V2nTSvsYUBHZEEAAA/u/i6k+XHLCeQym3PZYAEyG6KqbSe5PitUdr+BJIpKHlpphXmBDYYm5E+3fGGbSgjK58krRQOCXVv4XLgzwGF/26XaSXRq0u/SFAM7ruX5AwVEohgEiMcZO7EYkD/fLYeVRdyybFzUk148nNKAd19NEzaYDqub0tmh/xoL9atNi5GtsguJ4ycivz+1T6msy+9AAA"
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-daireler/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRngBAABXRUJQVlA4IGwBAACwBwCdASoYAB4APu1qsFAppaSiqAqpMB2JbAC1CGc9VbYFk5vi91Vbg3wNJ9Mq8fw5fyo6nPpJkNqouAkcq0Rm+XEt+W8AAP7tYWxjCSzSwI7kl0d9RJXGGqzcyagCLyEUIhlX4NLDZUUPDTtaUocBKqyxvEXifAECxQqn+HL+DVvyLTTkXAK1oesao8sf/HqSAugT0m/BhG32FEJuVOX2N4RJeBZV23vdxpR31hN+7v7I0/k38v9eynX/KRnHxZJsbaBsznj4Xk2s3qok+clYuAmHttHQqlKXYjoZlXwif2tjzfKTp376cmre8UvJ7vkNGuO+VRSpY4sEdB5SBtk8jsFY+FzE0V0wWyiHozPa46Sjb2cE9qQS7PdfR/jc3aaDa/zuq6/EsrPt3Vq1H/iRyMhe+KOwrO7XDLNJBvSgqfoT47wCVynfrI11enMYkbaJ/2644w5AK9FsDljRVyhQ9W5unw0W9gXlzoAA"
      },
      {
        "src": "/works/ornek-afis-daireler/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAACwBQCdASoYAB4APuVepU2pJSOiMAwBIByJQBjS6/23+A2mm/waOAK7Bt21Y60tYhic4oTTpkAA/vDssxYu8rUtyUD8SPOfWD7Ja7jZq29gO0Bxv6FBvOhd97/1TJeu1OnrH6PuZM5E3r3MpydkOBE312GF6PTwBdnf1LfE3Q7Ln5s33y5N+rwtJmbkxbFJXfBobpAmAe4z4WBAAZzUdsh8XMk6bcJVSD50X3zdZayYHJAf3EeI+bMzmvFxroFA2LnCTJxOw+4wssx2AAA="
      }
    ]
  },
  {
    "slug": "ornek-afis-yedi",
    "category": "poster",
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Yedi",
      "en": "Seven"
    },
    "text": {
      "tr": "Atölyenin yedinci yılı için afiş: halftone bir gradyanın içinden büyüyen tek rakam, kâğıdın dokusuyla birleşen nokta sıklığı.",
      "en": "Poster for the studio's seventh year: a single numeral growing out of a halftone gradient whose dots merge with the paper's grain."
    },
    "client": null,
    "sample": true,
    "order": 3,
    "cover": {
      "src2048": "/works/ornek-afis-yedi/cover-2048.webp",
      "src1024": "/works/ornek-afis-yedi/cover-1024.webp",
      "src640": "/works/ornek-afis-yedi/cover-640.webp",
      "w": 1600,
      "h": 2000,
      "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoYAB4APtFUoU2oJKMiN+gBABoJQBmLBjRUQjVYuJKV9ENpRyQQAP7zc6V7pS9RHOHqxt0DeRQHNX5NPRWcDN2kvlAWHdk4w/KmKxEeLTX0jL4wfvnYxpUR1pIp0BqgI/q71HwVGD99h+9v89CVds7mMGVkcVUTZYwAAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-afis-yedi/gallery-1-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAQBQCdASoYAB4APuFWpU2opKOiN/qoARAcCWYAxxTIB7U1vqYSWLC4bzBWCwtSmfZQAP73CINHjEDDbOG6wqifSg/VKc/90cVrTRIIUQprsOI64ZiW0Q5AMp2IKR/1GIRw4Fd0Q44Ux729kGAai9nfgWbClLGU666wyuv2p/8EYDSCBkdPjczVgrPJQSuIFSk4k7jdtrJyfvSlIHaptB9AcmujALwkdkAAAA=="
      },
      {
        "src": "/works/ornek-afis-yedi/gallery-2-1600.webp",
        "w": 1600,
        "h": 2000,
        "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoYAB4APtlcok2oJaMiN/qoAQAbCUAZQAQtf7fp6qllpxXfHJCAAP70JMn8W5GDk+skTMGFhYPN2O7cuxH6+BgJlAxJOx6j81TrE6hT7xkSZTHfeP+Pe1+sYYjYLdF9HiVpgqn/ZzNkfTE8K82mPeOXlJ/20/jik1cAAA=="
      }
    ]
  },
  {
    "slug": "ornek-kitap-kagit",
    "category": "editorial",
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "InDesign",
      "Illustrator"
    ],
    "title": {
      "tr": "Kâğıt Üzerine",
      "en": "On Paper"
    },
    "text": {
      "tr": "Bir deneme kitabı için kapak ve iç düzen. Serif başlık, dar sütun, geniş kenar boşluğu; sırtta tek renk, kapakta kör kabartma.",
      "en": "Cover and interior for a book of essays. Serif title, narrow measure, generous margins; one colour on the spine, a blind emboss on the cover."
    },
    "client": null,
    "sample": true,
    "order": 4,
    "cover": {
      "src2048": "/works/ornek-kitap-kagit/cover-2048.webp",
      "src1024": "/works/ornek-kitap-kagit/cover-1024.webp",
      "src640": "/works/ornek-kitap-kagit/cover-640.webp",
      "w": 1500,
      "h": 2100,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoYACIAPu1mqk2ppaQiMAgBMB2JQBl8BDwACZPOwHHkdAD9AuMiRPTXz1FG9twshotjEyhCmIfyX1BUPwdx/3tNKHd5P2sz4tvgKybODxU3naBgAAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-kitap-kagit/gallery-1-1600.webp",
        "w": 1600,
        "h": 2240,
        "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBQCdASoYACIAPu1orU8ppiQiKrgMATAdiWkA0MwLNnPq4Wl4tgbHfcX7mHsAYAu3AAD+77uJLfdR+ovZXc6vAt/t2YEhxR13jQu0bzdezRXddisG6QMrUTQ9paL0OMRZ51SkBD5LA+SGYxaZO8yxhzYt/SY0pIunRbQ+3JhTNlLRjFiJfzUnQAA="
      },
      {
        "src": "/works/ornek-kitap-kagit/gallery-2-1600.webp",
        "w": 1500,
        "h": 2100,
        "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoYACIAPu1mqk2ppaQiMAgBMB2JQAALfXyOzlzUj27CAAD+T4dxqdEaAIDOkMZCjV6idAB9TIVPH/qMEeuJo5L1WelHfIps7EAug5GdmX4hDPvAAAA="
      }
    ]
  },
  {
    "slug": "ornek-ambalaj-etiket",
    "category": "packaging",
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator",
      "Photoshop"
    ],
    "title": {
      "tr": "Atölye Etiketi",
      "en": "Studio Label"
    },
    "text": {
      "tr": "Bir kâğıt kutusu için sarmalayan etiket. Ön yüzde mühür, yan yüzlerde ürün bilgisi; kesim çizgileri ve kırım payı bırakılmış.",
      "en": "A wrap-around label for a paper box. A seal on the front, product information on the sides; die-cut and fold allowances left in."
    },
    "client": null,
    "sample": true,
    "order": 5,
    "cover": {
      "src2048": "/works/ornek-ambalaj-etiket/cover-2048.webp",
      "src1024": "/works/ornek-ambalaj-etiket/cover-1024.webp",
      "src640": "/works/ornek-ambalaj-etiket/cover-640.webp",
      "w": 2000,
      "h": 1400,
      "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBQCdASoYABEAPu1mrE+ppaQiMBgIATAdiWgAqScl4l+QAAZlNP0/00+LKvA7e4AXyAD+t+/YQ2Aja4IuqLpLBceLj5ef7tYFrC4L/4KvxfldSefLipWYBFQ6jJKbWfjuUR5HxPUbcfCqz2HGXFKcfryOUfXd+rB/G4ru7Ovbuxc1cYQAAA=="
    },
    "gallery": [
      {
        "src": "/works/ornek-ambalaj-etiket/gallery-1-1600.webp",
        "w": 1600,
        "h": 1120,
        "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoYABEAPu1mqU2ppaQiMAgBMB2JaQDN/CHfwvJjDtF3lWUpDwAAAP7vs7EH9K0UIun4OHM0yvXmCER4xzgJCmvvKDbZvedtzOOY0LEj48+ABymFsQAAAA=="
      },
      {
        "src": "/works/ornek-ambalaj-etiket/gallery-2-1600.webp",
        "w": 1600,
        "h": 1120,
        "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBQCdASoYABEAPu1ssFCppiSiqAqpMB2JaAC/a0ciUAYSFELDeNMIjI6k8ehtSrfYAP7SOUUIzo/3udQRWN0ApbaEB+1mkwjgH2wr1HlcZtqcQirWAZer+2wyOnkj/aZLu0XeGmFdv41nkRlbegbf4H/Rh/8MP69fxOvEjkI37knKnAAAAA=="
      }
    ]
  },
  {
    "slug": "ornek-kimlik-eg",
    "category": "identity",
    "year": 2026,
    "role": {
      "tr": "Konsept ve tasarım",
      "en": "Concept and design"
    },
    "tools": [
      "Illustrator"
    ],
    "title": {
      "tr": "EG Monogramı",
      "en": "EG Monogram"
    },
    "text": {
      "tr": "İki harfin tek bir çizgide buluştuğu monogram; kartvizitte kör kabartma, afişte tek renk, ekranda hareketli.",
      "en": "A monogram where two letters meet in one stroke; blind-embossed on the card, single colour on the poster, animated on screen."
    },
    "client": null,
    "sample": true,
    "order": 6,
    "cover": {
      "src2048": "/works/ornek-kimlik-eg/cover-2048.webp",
      "src1024": "/works/ornek-kimlik-eg/cover-1024.webp",
      "src640": "/works/ornek-kimlik-eg/cover-640.webp",
      "w": 1600,
      "h": 1600,
      "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBACdASoYABgAPu1kqk+ppSOiMBgIATAdiUAZC7F+jfa65WFhMe2NAfOR3u/AAP7vtex9sXwxGUoNXgNuFlWaCSTO9e6TX2znf8lFsBhoBdkexvXU24J3Z4+/MD2cxvBA/SgpGFaMuy6YrBieXL3w715amLt8hdTN96W5fumP3hZCc2MQRtJqXexHN1z4YjTgwqBzOAA="
    },
    "gallery": [
      {
        "src": "/works/ornek-kimlik-eg/gallery-1-1600.webp",
        "w": 1600,
        "h": 1600,
        "blur": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAABwBQCdASoYABgAPu1uqlCppqOiqAqpMB2JaADIpBOSIqSfrQM6/mHIPBO1namGrfLT2haAAP77ondK+8P2zqcEFqzu/cVzVPjjV9qupBCiE593j/n/j21dCL7j4A/9wFsRzkuY/F3dNFFzkGUiBGpd3ZhbnnB80GL838UNFWq9QgK8iZqffA1yZugrE/8dWOegJrYYjq6Yt7vQaTKg5+uxs3GzTZ1syTo24fdvamb6EMsCh+gQ/f3kAW9YLm5n95i2/BsGh2EPovXL//cHxq6HmCitixQAAAA="
      },
      {
        "src": "/works/ornek-kimlik-eg/gallery-2-1600.webp",
        "w": 1600,
        "h": 1600,
        "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBACdASoYABgAPu1mpU2ppaMiMBgMATAdiUAZiwId/D7O66XMc0oBMXOzIAD+8pjSoC57fzvVlraQULpzdCeB39erFrz9Lk/05DexjEYLqr4ZN7sUNZPhMm+7+9gXQ3utK+Xl/dA7CQ01XC+dgWQyf7cKaXh6kV12kV1b/Uz6Gl2oAynvUbeHBZghtnDNAZAAAA=="
      }
    ]
  }
];
export const portrait: WorkImage | null = null;
